version: "3.9"

services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "80:80" # port exposed to outside world.
      - "443:443" # <--- add this line
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      - ./persistentdata/certbot/www:/var/www/certbot
      - ./persistentdata/static:/app/store/static  # /var/www/static
      - ./persistentdata/media:/app/store/media  # /var/www/media
  django-backend:
    restart: always
    build:
      context: ./store
    image: djangobackend
    volumes:
      - ./persistentdata/static:/app/store/static # <--here /var/www/static
      - ./persistentdata/media:/app/store/media # <--here /var/www/media
    #depends_on:
    #  - nginx

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      - ./persistentdata/certbot/www:/var/www/certbot

# postgresql-db:
#   restart: always
#   image: postgres
#   volumes:
#           - ./persistentdata/db:/var/lib/postgresql/data
#   env_file:
#     - ./postgresql-db/.pg-env # why - see the next step